<?php

/**
 * @file
 * Contains po_translations_report.module
 */

/**
 * Implements hook_help().
 */
function po_translations_report_help($path, $arg) {
  switch ($path) {
    case 'admin/help#po_translations_report':
      $output = t('Get translation status of strings that are in po files stored in a folder.');
      return $output;

  }
}

/**
 * Implements hook_permission().
 */
function po_translations_report_permission() {
  return array(
    'access po translations report' => array(
      'title' => t('Access po translations report'),
    ),
  );
}

